name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Locate solution
        shell: pwsh
        run: |
          $sol = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
          if (-not $sol) { throw "No .sln found" }
          echo "SOLUTION_PATH=$($sol.FullName)" >> $env:GITHUB_ENV

      - name: Restore
        shell: cmd
        run: nuget restore "%SOLUTION_PATH%"

      - name: Build Release
        shell: cmd
        run: msbuild "%SOLUTION_PATH%" /p:Configuration=Release /m

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileFormatConverter-Release
          path: |
            **/bin/Release/**